packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: false
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@splinetool/runtime@2.0.10'
