'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {
  QrCode,
  Smartphone,
  Timer,
  CreditCard,
  Sparkles,
  ArrowRight,
  Plus,
  Minus,
  CheckCircle2,
} from 'lucide-react';
import { InteractiveTableStandee } from '@/components/landing/InteractiveTableStandee';
import { ThemeToggle } from '@/components/ui/theme-toggle';

const QR_FEATURES = [
  {
    icon: QrCode,
    title: 'Zero App Installs Required',
    desc: 'Guests point their native camera at the table QR code and the digital menu loads instantly in mobile Safari or Chrome.',
  },
  {
    icon: Smartphone,
    title: 'Visual Digital Menu with Modifiers',
    desc: 'Showcase rich dish photography, dietary tags (Veg/Non-Veg/Vegan), custom portion sizes, and spice preferences.',
  },
  {
    icon: Timer,
    title: 'Live Kitchen Cooking Countdown',
    desc: 'Once the kitchen accepts the ticket, the guest’s screen displays a live timer showing when their food will arrive hot.',
  },
  {
    icon: CreditCard,
    title: 'Direct UPI QR & Split Bill Checkout',
    desc: 'Customers view their itemized bill total and settle immediately via your uploaded UPI QR code with zero commission.',
  },
];

const QR_FAQS = [
  {
    q: 'How does table QR code ordering work in a restaurant?',
    a: 'Each dining table gets a unique QR standee generated by Kafei. When a guest scans the QR with their smartphone, the restaurant’s live digital menu opens instantly. The guest selects dishes and places the order, which automatically routes to the kitchen display screen with table number attached.',
  },
  {
    q: 'Can guests add items in multiple rounds to the same table bill?',
    a: 'Yes! If guests order drinks first and food 30 minutes later, each round joins the same active table session under its own order token, consolidating automatically at checkout.',
  },
  {
    q: 'Do I have to pay per order or transaction fee on QR orders?',
    a: 'No. Kafei charges a flat monthly subscription with 0% commission on orders. All payments go directly from the guest to your UPI/bank account.',
  },
];

export default function QrCodeOrderingSystemPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <Image
              src="/logo.png"
              alt="Kafei"
              width={32}
              height={32}
              className="h-7 w-auto object-contain rounded-md"
            />
            <span className="font-display text-lg font-extrabold text-foreground">Kafei</span>
          </Link>
          <div className="flex items-center gap-4">
            <ThemeToggle />
            <Link
              href="/login"
              className="text-[13px] text-muted-foreground hover:text-foreground transition-colors"
            >
              Sign In
            </Link>
            <Link
              href="/signup"
              className="rounded-lg bg-primary px-4 py-2 text-[13px] font-semibold text-background hover:bg-primary-hover transition-colors"
            >
              Start Free Trial
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="mx-auto max-w-6xl px-6 pt-16 pb-20 sm:pt-24 sm:pb-28">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-6 space-y-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3.5 py-1 font-mono text-[11px] uppercase tracking-wider text-primary">
              <Sparkles className="h-3.5 w-3.5" />
              Contactless Table QR Ordering
            </div>
            <h1 className="font-display text-3xl sm:text-5xl font-extrabold tracking-tight text-foreground leading-[1.1]">
              Table QR Ordering Built for Faster Table Turnover
            </h1>
            <p className="text-[16px] sm:text-[17px] leading-relaxed text-muted-foreground">
              Empower your guests to scan, browse dish photos, customize variants, and place orders directly to the kitchen without waiting for a waiter.
            </p>
            <div className="flex flex-col sm:flex-row items-center gap-4 pt-2">
              <Link
                href="/signup"
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-7 py-3.5 text-[15px] font-semibold text-background hover:bg-primary-hover transition-colors shadow-lg"
              >
                Get Started Free
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link
                href="/contact"
                className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-lg border border-border px-6 py-3.5 text-[15px] font-medium text-foreground hover:bg-secondary transition-colors"
              >
                Talk to Sales
              </Link>
            </div>
          </div>
          <div className="lg:col-span-6">
            <InteractiveTableStandee />
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="border-t border-border bg-card/20 px-6 py-20 sm:py-28">
        <div className="mx-auto max-w-6xl">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="font-display text-2xl sm:text-4xl font-bold tracking-tight text-foreground">
              Why Guests & Restaurant Staff Love Kafei QR Ordering
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {QR_FEATURES.map((f) => {
              const Icon = f.icon;
              return (
                <div
                  key={f.title}
                  className="rounded-xl border border-border bg-background p-6 space-y-3 hover:border-primary/40 transition-colors shadow-sm"
                >
                  <span className="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary border border-primary/20">
                    <Icon className="h-5 w-5" />
                  </span>
                  <h3 className="font-display text-lg font-semibold text-foreground">{f.title}</h3>
                  <p className="text-[14px] leading-relaxed text-muted-foreground">{f.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* FAQs */}
      <section className="border-t border-border px-6 py-20 sm:py-28">
        <div className="mx-auto max-w-4xl">
          <div className="text-center mb-14">
            <h2 className="font-display text-2xl sm:text-4xl font-bold tracking-tight text-foreground">
              Frequently Asked Questions About Table QR Ordering
            </h2>
          </div>

          <div className="space-y-4">
            {QR_FAQS.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div
                  key={faq.q}
                  className="rounded-xl border border-border bg-card/40 overflow-hidden"
                >
                  <button
                    type="button"
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="flex w-full items-center justify-between p-6 text-left"
                  >
                    <span className="font-display text-[16px] font-semibold text-foreground">
                      {faq.q}
                    </span>
                    {isOpen ? (
                      <Minus className="h-4 w-4 shrink-0 text-primary" />
                    ) : (
                      <Plus className="h-4 w-4 shrink-0 text-muted-foreground" />
                    )}
                  </button>
                  {isOpen && (
                    <div className="px-6 pb-6 pt-1 border-t border-border/40 text-[14px] leading-relaxed text-muted-foreground">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-12 px-6 text-center text-xs text-muted-foreground">
        <div className="mx-auto max-w-6xl flex flex-col sm:flex-row items-center justify-between gap-4">
          <p>© {new Date().getFullYear()} Kafei Technologies. All rights reserved.</p>
          <div className="flex gap-6">
            <Link href="/" className="hover:text-foreground">Home</Link>
            <Link href="/restaurant-billing-software" className="hover:text-foreground">Billing Software</Link>
            <Link href="/restaurant-pos-system" className="hover:text-foreground">POS System</Link>
            <Link href="/pricing" className="hover:text-foreground">Pricing</Link>
            <Link href="/contact" className="hover:text-foreground">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
