/**
 * Atlas V2.3 Centralized Metric & Dimension Registry
 * Single Source of Truth for Custom Report Definitions
 */

export const DATA_SOURCES = {
  SALES: 'SALES',
  ORDERS: 'ORDERS',
  MENU: 'MENU',
  CUSTOMERS: 'CUSTOMERS',
  STAFF: 'STAFF',
  BRANCHES: 'BRANCHES',
  PAYMENTS: 'PAYMENTS',
} as const;

export type DataSourceType = (typeof DATA_SOURCES)[keyof typeof DATA_SOURCES];

export interface MetricDefinition {
  key: string;
  name: string;
  unit: 'INR' | 'COUNT' | 'PERCENT' | 'MINUTES';
  description: string;
  dataSource: DataSourceType;
}

export const APPROVED_METRICS: Record<string, MetricDefinition> = {
  // SALES
  GROSS_SALES: {
    key: 'GROSS_SALES',
    name: 'Gross Sales',
    unit: 'INR',
    description: 'Sum of all placed order totals',
    dataSource: 'SALES',
  },
  NET_SALES: {
    key: 'NET_SALES',
    name: 'Net Revenue',
    unit: 'INR',
    description: 'Subtotal minus discounts for non-cancelled orders',
    dataSource: 'SALES',
  },
  TAX_AMOUNT: {
    key: 'TAX_AMOUNT',
    name: 'Taxes Collected',
    unit: 'INR',
    description: 'GST and tax total',
    dataSource: 'SALES',
  },
  DISCOUNT_AMOUNT: {
    key: 'DISCOUNT_AMOUNT',
    name: 'Discounts Waived',
    unit: 'INR',
    description: 'Total monetary value waived',
    dataSource: 'SALES',
  },
  REFUND_AMOUNT: {
    key: 'REFUND_AMOUNT',
    name: 'Refunds Processed',
    unit: 'INR',
    description: 'Total returned to customers',
    dataSource: 'SALES',
  },
  CANCELLED_AMOUNT: {
    key: 'CANCELLED_AMOUNT',
    name: 'Cancelled Value',
    unit: 'INR',
    description: 'Lost revenue from cancelled orders',
    dataSource: 'SALES',
  },
  AVERAGE_ORDER_VALUE: {
    key: 'AVERAGE_ORDER_VALUE',
    name: 'Average Order Value (AOV)',
    unit: 'INR',
    description: 'Settled revenue divided by completed orders',
    dataSource: 'SALES',
  },
  TOTAL_ORDERS: {
    key: 'TOTAL_ORDERS',
    name: 'Total Orders',
    unit: 'COUNT',
    description: 'Number of orders placed',
    dataSource: 'SALES',
  },

  // ORDERS
  COMPLETED_ORDERS: {
    key: 'COMPLETED_ORDERS',
    name: 'Completed Orders',
    unit: 'COUNT',
    description: 'Orders successfully delivered and closed',
    dataSource: 'ORDERS',
  },
  CANCELLED_ORDERS: {
    key: 'CANCELLED_ORDERS',
    name: 'Cancelled Orders',
    unit: 'COUNT',
    description: 'Orders cancelled during lifecycle',
    dataSource: 'ORDERS',
  },
  DINE_IN_COUNT: {
    key: 'DINE_IN_COUNT',
    name: 'Dine-In Orders',
    unit: 'COUNT',
    description: 'Orders placed on tables',
    dataSource: 'ORDERS',
  },
  TAKEOUT_COUNT: {
    key: 'TAKEOUT_COUNT',
    name: 'Takeout Orders',
    unit: 'COUNT',
    description: 'Direct / takeaway orders',
    dataSource: 'ORDERS',
  },

  // MENU
  UNITS_SOLD: {
    key: 'UNITS_SOLD',
    name: 'Units Sold',
    unit: 'COUNT',
    description: 'Quantity of menu items sold',
    dataSource: 'MENU',
  },
  GROSS_REVENUE: {
    key: 'GROSS_REVENUE',
    name: 'Item Gross Revenue',
    unit: 'INR',
    description: 'Total sales value generated by item',
    dataSource: 'MENU',
  },
  DISCOUNT_IMPACT: {
    key: 'DISCOUNT_IMPACT',
    name: 'Discount Impact',
    unit: 'INR',
    description: 'Discounts applied to item',
    dataSource: 'MENU',
  },
  REVENUE_SHARE_PERCENT: {
    key: 'REVENUE_SHARE_PERCENT',
    name: 'Revenue Share',
    unit: 'PERCENT',
    description: 'Percentage of total menu revenue',
    dataSource: 'MENU',
  },

  // CUSTOMERS
  TOTAL_CUSTOMERS: {
    key: 'TOTAL_CUSTOMERS',
    name: 'Unique Customers',
    unit: 'COUNT',
    description: 'Distinct customer profiles',
    dataSource: 'CUSTOMERS',
  },
  NEW_CUSTOMERS: {
    key: 'NEW_CUSTOMERS',
    name: 'New Customers',
    unit: 'COUNT',
    description: 'Customers with first order in period',
    dataSource: 'CUSTOMERS',
  },
  RETURNING_CUSTOMERS: {
    key: 'RETURNING_CUSTOMERS',
    name: 'Returning Customers',
    unit: 'COUNT',
    description: 'Repeat customer count',
    dataSource: 'CUSTOMERS',
  },
  REPEAT_RATE: {
    key: 'REPEAT_RATE',
    name: 'Repeat Purchase Rate',
    unit: 'PERCENT',
    description: 'Percentage of customers ordering >= 2 times',
    dataSource: 'CUSTOMERS',
  },
  LIFETIME_VALUE: {
    key: 'LIFETIME_VALUE',
    name: 'Average Lifetime Spend',
    unit: 'INR',
    description: 'Average total spend per customer',
    dataSource: 'CUSTOMERS',
  },

  // STAFF
  ORDERS_HANDLED: {
    key: 'ORDERS_HANDLED',
    name: 'Orders Handled',
    unit: 'COUNT',
    description: 'Orders serviced by staff member',
    dataSource: 'STAFF',
  },
  TOTAL_ACTIONS: {
    key: 'TOTAL_ACTIONS',
    name: 'Total Operational Actions',
    unit: 'COUNT',
    description: 'Total recorded activity events',
    dataSource: 'STAFF',
  },

  // BRANCHES
  BRANCH_REVENUE: {
    key: 'BRANCH_REVENUE',
    name: 'Branch Revenue',
    unit: 'INR',
    description: 'Total revenue attributed to branch',
    dataSource: 'BRANCHES',
  },
  CANCELLATION_RATE: {
    key: 'CANCELLATION_RATE',
    name: 'Cancellation Rate',
    unit: 'PERCENT',
    description: 'Percentage of cancelled orders',
    dataSource: 'BRANCHES',
  },
  NETWORK_SHARE_PERCENT: {
    key: 'NETWORK_SHARE_PERCENT',
    name: 'Network Share',
    unit: 'PERCENT',
    description: 'Share of total restaurant chain revenue',
    dataSource: 'BRANCHES',
  },

  // PAYMENTS
  PAYMENT_VOLUME: {
    key: 'PAYMENT_VOLUME',
    name: 'Payment Volume',
    unit: 'INR',
    description: 'Total settled monetary volume',
    dataSource: 'PAYMENTS',
  },
  TRANSACTION_COUNT: {
    key: 'TRANSACTION_COUNT',
    name: 'Transaction Count',
    unit: 'COUNT',
    description: 'Number of settled payment transactions',
    dataSource: 'PAYMENTS',
  },
};

export const APPROVED_DIMENSIONS = {
  DATE_DAY: {
    key: 'DATE_DAY',
    name: 'Day',
    description: 'Group by calendar date',
  },
  DATE_WEEK: {
    key: 'DATE_WEEK',
    name: 'Week',
    description: 'Group by calendar week',
  },
  DATE_MONTH: {
    key: 'DATE_MONTH',
    name: 'Month',
    description: 'Group by calendar month',
  },
  DATE_HOUR: {
    key: 'DATE_HOUR',
    name: 'Hour of Day',
    description: 'Group by hour (0..23)',
  },
  BRANCH: {
    key: 'BRANCH',
    name: 'Branch',
    description: 'Group by restaurant branch',
  },
  MENU_ITEM: {
    key: 'MENU_ITEM',
    name: 'Menu Item',
    description: 'Group by individual dish',
  },
  MENU_CATEGORY: {
    key: 'MENU_CATEGORY',
    name: 'Menu Category',
    description: 'Group by category',
  },
  STAFF_MEMBER: {
    key: 'STAFF_MEMBER',
    name: 'Staff Member',
    description: 'Group by employee',
  },
  PAYMENT_METHOD: {
    key: 'PAYMENT_METHOD',
    name: 'Payment Method',
    description: 'Group by Cash, Card, UPI, etc.',
  },
  ORDER_TYPE: {
    key: 'ORDER_TYPE',
    name: 'Order Type',
    description: 'Group by Dine-in vs Takeout',
  },
  ORDER_STATUS: {
    key: 'ORDER_STATUS',
    name: 'Order Status',
    description: 'Group by lifecycle status',
  },
  CUSTOMER_SEGMENT: {
    key: 'CUSTOMER_SEGMENT',
    name: 'Customer Segment',
    description: 'Group by New, Frequent, High-Value, etc.',
  },
} as const;

export const FILTER_OPERATORS = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS',
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN',
  GREATER_EQUAL: 'GREATER_EQUAL',
  LESS_EQUAL: 'LESS_EQUAL',
  CONTAINS: 'CONTAINS',
  IN: 'IN',
  NOT_IN: 'NOT_IN',
} as const;

export const DATE_PRESETS = {
  TODAY: 'TODAY',
  YESTERDAY: 'YESTERDAY',
  THIS_WEEK: 'THIS_WEEK',
  LAST_WEEK: 'LAST_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  LAST_MONTH: 'LAST_MONTH',
  THIS_QUARTER: 'THIS_QUARTER',
  LAST_QUARTER: 'LAST_QUARTER',
  THIS_YEAR: 'THIS_YEAR',
  LAST_YEAR: 'LAST_YEAR',
  CUSTOM: 'CUSTOM',
} as const;

export const VISUALIZATION_TYPES = {
  KPI_CARD: 'KPI_CARD',
  TABLE: 'TABLE',
  BAR_CHART: 'BAR_CHART',
  LINE_CHART: 'LINE_CHART',
  DONUT_CHART: 'DONUT_CHART',
  AREA_CHART: 'AREA_CHART',
} as const;
